### ISSUE TITLE
Template finder don't resolve value for variables with yaml structure.

### ISSUE THREAD

**Issue by salbertperso** [ArtyMaury/template-finder#8]
Hi,

I have a variable with a yaml structure

```yaml
vars:
   - routing_priority:
        log_services: 1
        deployment_services: 2
        ....
```
In my playbbok, when i call routing_priority variable i get an undefined value
